# Generated by Django 2.2.20 on 2022-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
