# Generated by Django 3.2.12 on 2022-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactAndAbout', '0002_messagecontact_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
