# Generated by Django 2.2.20 on 2022-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactAndAbout', '0003_alter_messagecontact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallMessage', models.TextField(blank=True, null=True)),
                ('freeDelivry', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='Signatures')),
            ],
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
