# Generated by Django 2.2.20 on 2022-08-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactAndAbout', '0004_auto_20220820_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
