# Generated by Django 2.2.20 on 2022-03-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminProduct', '0007_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('mainImg', models.ImageField(blank=True, null=True, upload_to='products/Images principales')),
                ('othersImgs', models.ImageField(blank=True, null=True, upload_to='products/Autres images')),
                ('colors', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('colorVariation', models.TextField(blank=True, null=True)),
                ('sizeVariation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminProduct.Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminProduct.Category')),
                ('sizes', models.ManyToManyField(blank=True, to='adminProduct.Size')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminProduct.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
