# Generated by Django 2.2.20 on 2022-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0002_registerproduct_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerproduct',
            old_name='colorVariation',
            new_name='colorimgs',
        ),
        migrations.RemoveField(
            model_name='registerproduct',
            name='sizeVariation',
        ),
        migrations.RemoveField(
            model_name='registerproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registerproduct',
            name='colorsImgs',
            field=models.ImageField(blank=True, null=True, upload_to='products/Colors images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='products/Mains Images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='othersImgs',
            field=models.ImageField(blank=True, null=True, upload_to='products/Others images'),
        ),
    ]
