# Generated by Django 2.2.20 on 2022-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0003_auto_20220401_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproduct',
            name='tabOtherImgs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
