# Generated by Django 2.2.20 on 2022-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0004_registerproduct_tabotherimgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproduct',
            name='colorsImgs',
            field=models.ImageField(blank=True, null=True, upload_to='products/Colors_images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='products/Mains_Images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='othersImgs',
            field=models.ImageField(blank=True, null=True, upload_to='products/Others_images'),
        ),
    ]
