# Generated by Django 2.2.20 on 2022-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0005_auto_20220402_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproduct',
            name='validateProd',
            field=models.BooleanField(default=False),
        ),
    ]
