# Generated by Django 2.2.20 on 2022-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0006_registerproduct_validateprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproduct',
            name='secondImg',
            field=models.ImageField(blank=True, null=True, upload_to='products/Mains_Images'),
        ),
    ]
