# Generated by Django 2.2.20 on 2022-07-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0007_registerproduct_secondimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerproduct',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registerProduct', to='adminProduct.Category'),
        ),
    ]
