# Generated by Django 2.2.20 on 2022-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0010_auto_20220820_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproduct',
            name='rejectReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
