# Generated by Django 2.2.20 on 2022-11-09 11:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0011_registerproduct_rejectreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerproduct',
            name='colorsImgs',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='products/Others_images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='mainImg',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='products/Mains_Images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='othersImgs',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='products/Others_images'),
        ),
        migrations.AlterField(
            model_name='registerproduct',
            name='secondImg',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='products/Mains_Images'),
        ),
    ]
