# Generated by Django 2.2.20 on 2022-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
