# Generated by Django 2.2.20 on 2022-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
