# Generated by Django 2.2.20 on 2022-08-09 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
