# Generated by Django 2.2.20 on 2022-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220315_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
