# Generated by Django 2.2.20 on 2022-05-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20220326_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tfa_secret',
        ),
    ]
