# Generated by Django 2.2.20 on 2022-06-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_user_tfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountMoney',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
