# Generated by Django 2.2.20 on 2022-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20220618_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logoShop',
            field=models.ImageField(blank=True, null=True, upload_to='Images/LogoShop'),
        ),
        migrations.AddField(
            model_name='user',
            name='nameShop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
