# Generated by Django 2.2.20 on 2022-06-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminProduct', '0007_brand'),
        ('authentication', '0017_auto_20220619_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logoShop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nameShop',
        ),
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminProduct.Brand'),
        ),
    ]
