# Generated by Django 2.2.20 on 2022-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20220625_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nameShop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
