# Generated by Django 2.2.20 on 2022-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20220820_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
