# Generated by Django 2.2.20 on 2022-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityAndRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidentiality', models.TextField(blank=True, null=True)),
                ('rulerSeller', models.TextField(blank=True, null=True)),
                ('rulerBuyer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
