# Generated by Django 2.2.20 on 2022-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0002_confidentialityandrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
