# Generated by Django 2.2.20 on 2022-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0004_settingsite_namesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='mtnMoney',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='orangeMoney',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
