# Generated by Django 2.2.20 on 2022-07-07 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0006_visitor_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 7, 10, 22, 18, 161843, tzinfo=utc)),
        ),
    ]
