# Generated by Django 2.2.20 on 2022-08-01 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0007_auto_20220707_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 1, 10, 59, 39, 908392, tzinfo=utc)),
        ),
    ]
