# Generated by Django 2.2.20 on 2022-08-03 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0008_auto_20220801_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(blank=True, max_length=50, null=True)),
                ('emailHost', models.CharField(blank=True, max_length=255, null=True)),
                ('emailHostUser', models.CharField(blank=True, max_length=255, null=True)),
                ('passwordUser', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 3, 8, 38, 45, 911627, tzinfo=utc)),
        ),
    ]
