# Generated by Django 2.2.20 on 2022-08-03 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0009_auto_20220803_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersetting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 3, 8, 51, 32, 689545, tzinfo=utc)),
        ),
    ]
