# Generated by Django 2.2.20 on 2022-08-03 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0010_auto_20220803_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othersetting',
            old_name='secret_key',
            new_name='secret_k',
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 3, 8, 52, 49, 349911, tzinfo=utc)),
        ),
    ]
