# Generated by Django 2.2.20 on 2022-08-03 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0011_auto_20220803_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 3, 8, 57, 26, 922537, tzinfo=utc)),
        ),
    ]
