# Generated by Django 2.2.20 on 2022-08-09 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0014_auto_20220809_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 9, 15, 22, 21, 377025, tzinfo=utc)),
        ),
    ]
