# Generated by Django 2.2.20 on 2022-08-20 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0018_auto_20220820_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='ourSlogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 20, 7, 28, 7, 798544, tzinfo=utc)),
        ),
    ]
