# Generated by Django 2.2.20 on 2022-09-04 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0020_auto_20220820_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 4, 5, 23, 28, 295728, tzinfo=utc)),
        ),
    ]
