# Generated by Django 2.2.20 on 2022-10-11 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0021_auto_20220904_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 11, 15, 7, 41, 371124, tzinfo=utc)),
        ),
    ]
