# Generated by Django 2.2.20 on 2022-11-09 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0024_auto_20221109_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 9, 9, 4, 0, 386757, tzinfo=utc)),
        ),
    ]
