# Generated by Django 2.2.20 on 2022-11-09 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0025_auto_20221109_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 9, 10, 53, 3, 697951, tzinfo=utc)),
        ),
    ]
