# Generated by Django 2.2.20 on 2022-11-09 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0027_auto_20221109_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsite',
            name='fav_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='Images/SettingSites'),
        ),
        migrations.AlterField(
            model_name='settingsite',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='Images/SettingSites'),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 9, 11, 20, 28, 614912, tzinfo=utc)),
        ),
    ]
