# Generated by Django 2.2.20 on 2022-11-11 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0028_auto_20221109_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='orangeNber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 11, 15, 24, 41, 66994, tzinfo=utc)),
        ),
    ]
