# Generated by Django 2.2.20 on 2022-11-12 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0029_auto_20221111_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='link_whatsapp_grpe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsite',
            name='orangeNber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero orange'),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 13, 35, 3, 60307, tzinfo=utc)),
        ),
    ]
