# Generated by Django 2.2.20 on 2022-11-13 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('settingSite', '0030_auto_20221112_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='link_instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor_infos',
            name='event_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 13, 0, 22, 18, 888144, tzinfo=utc)),
        ),
    ]
