# Generated by Django 2.2.20 on 2022-04-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
