# Generated by Django 2.2.20 on 2022-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerProduct', '0007_registerproduct_secondimg'),
        ('handleCart', '0002_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='registerProduct.RegisterProduct'),
        ),
    ]
