# Generated by Django 2.2.20 on 2022-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0004_auto_20220429_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
