# Generated by Django 2.2.20 on 2022-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0007_auto_20220430_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pathImg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
