# Generated by Django 2.2.20 on 2022-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0008_orderitem_pathimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
