# Generated by Django 2.2.20 on 2022-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0009_orderitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
