# Generated by Django 2.2.20 on 2022-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0013_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupongerate',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupongerate',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
