# Generated by Django 2.2.20 on 2022-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0014_auto_20220515_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='newTotal',
        ),
        migrations.AddField(
            model_name='order',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
