# Generated by Django 2.2.20 on 2022-05-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0015_auto_20220515_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupongerate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
