# Generated by Django 2.2.20 on 2022-05-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0017_shippingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handleCart.ShippingAdress'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
