# Generated by Django 2.2.20 on 2022-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0021_auto_20220520_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commandProducts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
