# Generated by Django 2.2.20 on 2022-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0022_order_commandproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cartNumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='nberInvoice',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
