# Generated by Django 2.2.20 on 2022-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0023_auto_20220521_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nberInvoice',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
