# Generated by Django 2.2.20 on 2022-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0025_auto_20220521_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priceDelivery',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
