# Generated by Django 2.2.20 on 2022-05-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0002_auto_20220519_1025'),
        ('handleCart', '0026_order_pricedelivery'),
    ]

    operations = [
    ]
