# Generated by Django 2.2.20 on 2022-05-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0028_auto_20220528_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
