# Generated by Django 2.2.20 on 2022-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0029_auto_20220528_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='ouvert', max_length=20),
        ),
    ]
