# Generated by Django 2.2.20 on 2022-05-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0030_auto_20220528_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payement_complete',
            new_name='delivered',
        ),
    ]
