# Generated by Django 2.2.20 on 2022-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handleCart', '0031_auto_20220528_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priceDelivery',
            field=models.FloatField(default=0),
        ),
    ]
