# Generated by Django 2.2.20 on 2022-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminProduct', '0002_auto_20220319_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/subCategory'),
        ),
    ]
