# Generated by Django 2.2.20 on 2022-03-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminProduct', '0005_auto_20220321_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COlor',
        ),
    ]
