# Generated by Django 2.2.20 on 2022-11-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminProduct', '0010_auto_20221109_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='imageBrand',
            new_name='image',
        ),
    ]
